# Generated by Django 3.0.2 on 2020-08-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='publish',
            field=models.DateTimeField(),
        ),
    ]
