# Generated by Django 3.0.2 on 2020-08-17 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0002_auto_20200817_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='publish',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
